version: 1.0.{build}.{branch}

matrix:
  fast_finish: false

environment:
  matrix:

    # Pre-installed Python versions.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PY_STR: "2.6"
    - PY_STR: "2.6-32"
    - PY_STR: "2.7"
    - PY_STR: "2.7-32"
    - PY_STR: "3.3"
    - PY_STR: "3.3-32"
    - PY_STR: "3.4"
    - PY_STR: "3.4-32"
    - PY_STR: "3.5"
    - PY_STR: "3.5-32"
    - PY_STR: "3.6"
    - PY_STR: "3.6-32"

install:
  - SET PYLAUNCH_DEBUG=1
  - C:\Python36-x64\python.exe .\view_winreg.py

test_script:
  - py.exe -%PY_STR% -c "import sys; print(sys.version)"
